module

public import Cli.Basic
public import Common.Flags
import Common.Errors
public import Driver.Pipeline
-- `fugueVersion`, the string every `[Cli|…]` block below is stamped with. Generated by
-- `lakefile.lean` into `.lake/version/` from the `Fugue` package's `version` field, which is the
-- one place the compiler's version is written; see `versionModule` there for why the value
-- travels as a source file rather than as a Lean option.
public import Version
-- `Diagnostics.embeddedPages`, the `fugue explain` corpus baked into the binary. Generated by
-- `lakefile.lean` from `docs/diagnostics/`; see `diagnosticPagesModule` there. Imported twice —
-- plain for `diagnosticPage`'s runtime use, `meta` for the `#guard`s that check the corpus against
-- the registry (`#guard` elaborates in a `meta` context, as does the registry re-export below).
public import DiagnosticPages
meta import DiagnosticPages
meta import Common.Diagnostics.Registry
import ProgressBar
import Colorized

public section

open Cli
open Colorized (Colorized)

/-- The input source: a file path, or `-` to read from standard input. -/
inductive Input : Type
  | path : System.FilePath → Input
  | stdin
  deriving Inhabited

@[no_expose]
instance : ToString Input where
  toString
    | .path p => toString p
    | .stdin => "-"

instance : ParseableType System.FilePath where
  name := "path"
  parse? str := some ↑str

instance : ParseableType Input where
  name := "path|-"
  parse?
    | "-" => some .stdin
    | str => some (.path ↑str)

/-- The `<name>[:<value>]` shape shared by `-d`/`-f`/`-X`'s options.

**`:`, not `=`.** `leanprover/Cli` splits a long flag on its own first `=`, so a `=`-separated
option value would read `--debug=dump-dir=/tmp/x` — the same character doing two different jobs in
one word — and, worse, would be split by Cli *before* short-name matching, making the attached
form `-ddump-dir=/tmp/x` parse as a flag literally named `-ddump-dir`. `:` sidesteps both: it is
ordinary to Cli, so the attached and separated spellings work identically with no argument
rewriting. It is also the established spelling for this shape of flag — `javac -Xlint:all`,
`scalac -Xprint:typer`. -/
structure NamedOption : Type where
  name : String
  value : Option String
  deriving Inhabited

instance : ParseableType NamedOption where
  name := "<name>[:<value>]"
  -- Only the *first* `:` separates: everything after it is the value, colons and all, so a
  -- Windows path or a URL survives being one.
  parse? str := match str.splitOn ":" with
    | [] => none
    | [name] => some { name, value := none }
    | name :: rest => some { name, value := some (String.intercalate ":" rest) }

/-- The `<name>` (enable) / `no-<name>` (disable) shape of `-W`'s per-warning toggles. -/
structure WarningToggle : Type where
  name : String
  enabled : Bool
  deriving Inhabited

instance : ParseableType WarningToggle where
  name := "<name>|no-<name>"
  parse? str :=
    if str.take 3 == "no-" then
      let name := str.drop 3 |>.toString
      if name.isEmpty then none else some { name, enabled := false }
    else if str.isEmpty then
      none
    else
      some { name := str, enabled := true }

instance : ParseableType Target where
  name := "go|join"
  parse?
    | "go" => some .go
    | "join" => some .join
    | _ => none

/-- One name a `-d`/`-f`/`-W`/`-X` flag accepts, with the value it takes and what it does.

The allowlist and the help text are the same table on purpose: an option that cannot be listed
cannot be accepted either, so `fugue help` cannot drift from what the parser takes. -/
private structure OptionDoc : Type where
  /-- The name, spelled as it is written after the flag. -/
  name : String
  /-- The value the option takes, as a placeholder (`<path>`), or `none` if it takes none. -/
  value : Option String := none
  /-- One line: what the option does. -/
  description : String

/-- How the option is written on the command line, value placeholder included. -/
private def OptionDoc.spelling (doc : OptionDoc) : String :=
  doc.value.elim doc.name λ v ↦ s!"{doc.name}:{v}"

/-- Render `docs` as a two-column block, one option per line, descriptions aligned past the
widest spelling. -/
private def OptionDoc.render (docs : List OptionDoc) : String :=
  let width := docs.foldl (λ w doc ↦ max w doc.spelling.length) 0
  String.intercalate "\n" <| docs.map λ doc ↦
    let pad := String.replicate (width - doc.spelling.length + 2) ' '
    s!"  {doc.spelling}{pad}{doc.description}"

/-- `-d<name>` options recognized: one `dump-<stage>` per stage with an artifact to write, derived
from `Stage` (`Common/Diagnostics/Stage.lean`) rather than listed here, plus `dump-dir`, which
configures where they go rather than naming a dump point of its own. Adding a stage and giving it
a flag are the same edit — `Stage.artifact?` is matched exhaustively, so a new stage cannot skip
the question, and what it answers is also what `fugue help -d` prints. -/
private def debugOptionDocs : List OptionDoc :=
  (Stage.list.filterMap λ s ↦ s.artifact?.map λ artifact ↦
    { name := s.dumpOption, description := s!"Write {artifact}." })
  ++ [ { name := "dump-dir", value := "<path>"
       , description := s!"Where the `dump-*` artifacts go. Defaults to `{defaultDumpDir}`." } ]

/-- `-f<name>` toggles recognized, derived from `Feature` (`Common/Flags.lean`) rather than
listed here: a toggle nothing can read cannot be accepted, and one a pass reads cannot be
rejected. -/
private def featureOptionDocs : List OptionDoc :=
  Feature.list.map λ f ↦ { name := f.name, description := f.description }

/-- `-W<name>` names recognized, derived from the diagnostic registry
(`Common/Diagnostics/Registry.lean`) rather than listed here: a warning cannot exist without a
registry entry, so it cannot exist without its `-W` name being accepted. Each is listed with the
code it suppresses, so `fugue help -W` and `fugue explain <code>` name the same thing. -/
private def warningOptionDocs : List OptionDoc :=
  Diagnostics.entries.filterMap λ e ↦
    if e.warningName.isEmpty then none
    else some { name := e.warningName, description := s!"{e.code}: {e.summary}" }

/-- `-X<name>[:<value>]` backend options. One table, not one per backend: an option a backend does
not understand is a mistake worth reporting either way, and the alternative is a table whose
contents depend on a flag parsed in the same pass.

`go-pkg` names the Go package the emitted file declares, defaulting to `main`. It is not a
`-f` toggle because it is a property of the *output*, not of how the compiler behaves; and not a
Go build tag, unlike the integer representation, because the compiler is what writes the
`package` clause. -/
private def targetOptionDocs : List OptionDoc :=
  [ { name := "go-pkg", value := "<name>"
    , description := "The package clause the emitted Go declares. Defaults to `main`." } ]

/-- A flag whose names `fugue help` explains one by one: the four that take a table of names
rather than a single value. -/
private inductive HelpTopic : Type
  | debug
  | feature
  | warn
  | target

namespace HelpTopic

/-- Every topic, in the order `fugue help` lists them. -/
private def list : List HelpTopic := [.debug, .feature, .warn, .target]

/-- The `compile` flag this topic explains, and the `fugue help` flag that selects it. -/
private def flag : HelpTopic → String
  | .debug => "d" | .feature => "f" | .warn => "W" | .target => "X"

/-- The topic's `fugue help` flag, spelled long — what `Cli.Parsed.hasFlag` matches on. -/
private def longFlag : HelpTopic → String
  | .debug => "debug" | .feature => "feature" | .warn => "warn" | .target => "X"

/-- What one of this flag's names is called in an error message ("unknown debug option 'x'"). -/
private def kind : HelpTopic → String
  | .debug => "debug option" | .feature => "feature toggle"
  | .warn => "warning" | .target => "target option"

/-- The names this flag accepts, with what each does. -/
private def options : HelpTopic → List OptionDoc
  | .debug => debugOptionDocs | .feature => featureOptionDocs
  | .warn => warningOptionDocs | .target => targetOptionDocs

/-- Just the names, for validating what was passed. -/
private def names (t : HelpTopic) : Array String := (t.options.map (·.name)).toArray

/-- How the flag is written on the command line, value shape included. -/
private def spelling : HelpTopic → String
  | .debug => "-d<name>[:<value>]"
  | .feature => "-f<name>"
  | .warn => "-W<name> / -Wno-<name>"
  | .target => "-X<name>[:<value>]"

/-- One line: what the flag is for. -/
private def summary : HelpTopic → String
  | .debug => "Debugging options: stage dumps, and where they are written."
  | .feature => "Feature toggles: how the compiler behaves, not what it emits."
  | .warn => "Per-warning control: `<name>` enables a warning, `no-<name>` silences it."
  | .target => "Backend options: properties of the emitted code."

/-- What `fugue compile --help` says about the flag: the summary, and where the names are. The
short form is derived from the long one rather than written twice. -/
private def flagDescription (t : HelpTopic) : String :=
  s!"{t.summary} Comma-separate to pass several. Run `fugue help -{t.flag}` for the names."

/-- Print the topic: how the flag is written, then one line per name it accepts. -/
private def print (t : HelpTopic) : IO Unit := do
  IO.println s!"{t.spelling}  {t.summary}"
  IO.println "Comma-separate names to pass several at once."
  IO.println ""
  IO.println (OptionDoc.render t.options)
  IO.println ""

end HelpTopic

/-- Collect `<name>[:<value>]` options into a map, rejecting an unknown or duplicate `name`. -/
private def NamedOption.toMap (topic : HelpTopic) (opts : Array NamedOption) : IO (Std.HashMap String (Option String)) := do
  let mut map : Std.HashMap String (Option String) := {}
  for opt in opts do
    unless topic.names.contains opt.name do
      throw ↑s!"unknown {topic.kind} '{opt.name}'. Known: {String.intercalate ", " topic.names.toList}. \
Run 'fugue help -{topic.flag}' for what each does."
    if map.contains opt.name then
      throw ↑s!"{topic.kind} '{opt.name}' specified multiple times."
    map := map.insert opt.name opt.value
  return map

/-- Collect `-W`'s toggles into a map, rejecting an unknown or duplicate `name`. -/
private def WarningToggle.toMap (toggles : Array WarningToggle) : IO (Std.HashMap String Bool) := do
  let known := HelpTopic.warn.names
  let mut map : Std.HashMap String Bool := {}
  for toggle in toggles do
    unless known.contains toggle.name do
      throw ↑s!"unknown warning '{toggle.name}'. Known: {String.intercalate ", " known.toList}. \
Run 'fugue help -W' for what each reports."
    if map.contains toggle.name then
      throw ↑s!"warning '{toggle.name}' specified multiple times."
    map := map.insert toggle.name toggle.enabled
  return map

/-- Cancel the given `spinner` with a persistent error message. -/
private abbrev Spinner.fail (spinner : Spinner) (msg : String) : IO Unit :=
  spinner.cancel (.persist "💥" msg)

/-- Cancel the given `spinner` with a persistent success message. -/
private abbrev Spinner.success (spinner : Spinner) (msg : String) : IO Unit :=
  spinner.cancel (.persist "🎉" msg)

/-- A real animated `Spinner`, or a quiet stand-in when `-fno-progress` disables the animation
(e.g. output being piped/logged, where a `\r`-redrawing spinner is just noise) — `runCli` calls
`.log`/`.setTitle`/`.fail`/`.success` the same way either way. `.quiet` never spins up a `Spinner`
at all (no background task), rather than merely hiding one's output. -/
private inductive Progress : Type
  | spinner (s : Spinner)
  | quiet

/-- Print `line` as its own line — matches `Spinner.log`, minus the animation. -/
private def Progress.log : Progress → String → IO Unit
  | .spinner s, line => s.log line
  | .quiet, line => IO.eprintln line

/-- Print `line` on `out` rather than on the stream the animation uses — matches
`Spinner.logOn`. Anything going to a handle other than the spinner's own must go through here:
written directly, it lands on top of the animation line, which nothing has erased. -/
private def Progress.logOn : Progress → IO.FS.Stream → String → IO Unit
  | .spinner s, out, line => s.logOn out line
  | .quiet, out, line => do
    out.putStr s!"{line}\n"
    out.flush

/-- Stop the animation, persisting `msg` in its place — like `.fail`/`.success`, but with no
dingbat, for a conclusion nothing else has claimed yet that isn't a fatal/success banner. For the
paths that end the process themselves: `IO.Process.exit` skips `withProgress`'s own cleanup, so
the animation line would otherwise stay on screen with whatever is printed next running into it. -/
private def Progress.stop (p : Progress) (msg : String) : IO Unit :=
  match p with
  | .spinner s => do
    unless ← s.isCancelled do
      s.cancel (.replace msg)
  | .quiet => IO.eprintln msg

/-- Update the current status — a no-op when `.quiet`, since there's nothing ongoing to label. -/
private def Progress.setTitle : Progress → String → IO Unit
  | .spinner s, title => s.setTitle title
  | .quiet, _ => pure ()

private def Progress.fail : Progress → String → IO Unit
  | .spinner s, msg => s.fail msg
  | .quiet, msg => IO.eprintln s!"💥 {msg}"

private def Progress.success : Progress → String → IO Unit
  | .spinner s, msg => s.success msg
  -- Standard error, like every other status line: `.spinner` draws on standard error too, and
  -- `-fno-progress` is for the runs whose standard output is being piped somewhere.
  | .quiet, msg => IO.eprintln s!"🎉 {msg}"

private def withProgress {α : Type} (flags : FlagsEnv) (msg : String) (act : Progress → IO α) : IO α := do
  if !flags.progress then
    act .quiet
  else
    let spinner ← Spinner.newOnStream Spinners.dotsCircle msg (← IO.getStderr)
    let res ← act (.spinner spinner)
    unless ← spinner.isCancelled do
      spinner.cancel .erase
    return res

/--
  Parses every flag out of `p` (rejecting unknown/duplicate `-d`/`-f`/`-W` names and a
  valueless `-d dump-dir`, per `NamedOption.toMap`/`WarningToggle.toMap` above) into the
  `FlagsEnv` the compile runs under. The one place all CLI-flag validation happens; the
  resulting value is handed to `runPipelineIO`, which supplies it to every pass as a reader.
-/
private def validateFlags (p : Parsed) : IO FlagsEnv := do
  let debug ← NamedOption.toMap .debug <| p.flag? "debug" |>.map (·.as! (Array NamedOption)) |>.getD #[]
  let features ← NamedOption.toMap .feature <| p.flag? "feature" |>.map (·.as! (Array NamedOption)) |>.getD #[]
  let warnings ← WarningToggle.toMap <| p.flag? "warn" |>.map (·.as! (Array WarningToggle)) |>.getD #[]
  let targetOptions ← NamedOption.toMap .target <| p.flag? "X" |>.map (·.as! (Array NamedOption)) |>.getD #[]
  let output := p.flag? "output" |>.map (·.as! System.FilePath)
  let target := p.flag? "target" |>.map (·.as! Target) |>.getD .go
  let searchPath := p.flag? "include" |>.map (·.as! (Array System.FilePath)) |>.getD #[] |>.toList

  match debug.get? "dump-dir" with
  | some none => throw ↑"debug option 'dump-dir' requires a path, e.g. -ddump-dir:.fugue/debug"
  | _ => pure ()

  match targetOptions.get? "go-pkg" with
  | some none => throw ↑"target option 'go-pkg' requires a name, e.g. -Xgo-pkg:pingpong"
  | _ => pure ()

  return { debug, features, warnings, targetOptions, output, target, searchPath }

private def runCli (p : Parsed) : IO UInt32 := do
  let flags ← validateFlags p

  let colored := flags.colored

  let input := p.positionalArg! "input" |>.as! Input
  let dumpName := match input with
    | .path path => path.fileName.getD (toString path)
    | .stdin => "stdin"
  let containingDir := match input with
    | .path path => path.parent
    | .stdin => none

  -- One spinner for the whole compile, Lean-`lake build`-style: just
  -- `[<done>/<discovered>] Running on module '<name>'…`, tracked here (not in
  -- `Driver/Modules.lean`, which only reports raw `onModuleProgress`/`onModuleEvent` facts).
  -- `<discovered>` grows as `EXTENDS` pulls in new modules; completed steps print as
  -- persisted lines via `Spinner.log` without interrupting the animation.
  withProgress flags "Reading input…" λ spinner ↦ do
    let source ← match input with
      | .path path =>
        unless ← path.pathExists do
          spinner.fail s!"File '{path}' does not exist."
          IO.Process.exit 1
        IO.FS.readFile path
      | .stdin => (← IO.getStdin).readToEnd
    let lines := source.split (· == '\n') |>.toList

    let discovered ← IO.mkRef (∅ : Std.HashSet String)
    -- A set, not a counter: `onModuleEvent` can fire more than once for the same name (`.built`
    -- once, `.replayed` for every later cache-hit reference), but must still count each module
    -- only once done.
    let done ← IO.mkRef (∅ : Std.HashSet String)

    -- A file's module must be named after the file; stdin has no filename, so nothing to check.
    let expectedName := match input with
      | .path path => path.fileStem
      | .stdin => none

    let result ← runPipelineIO flags source containingDir dumpName expectedName
      { onModuleEvent := λ name outcome ↦ do
          done.modify (·.insert name)
          let count := s!"[{(← done.get).size}/{(← discovered.get).size}]"
          let (dingbat, color, label) : String × Colorized.Color × String := match outcome with
            | .built hadWarnings => (if hadWarnings then "⚠" else "✔", if hadWarnings then .Yellow else .Green, "Built")
            | .replayed => ("✔", .Cyan, "Replayed")
            | .failed => ("✖", .Red, "Failed")
          spinner.log <| styleIf colored .Bold <| colorizeIf colored color s!"{dingbat} {count} {label} {name}"
        onModuleProgress := λ name ↦ do
          discovered.modify (·.insert name)
          spinner.setTitle s!"[{(← done.get).size}/{(← discovered.get).size}] Running on module '{name}'…"
        logLine := λ line ↦ spinner.log line }

    -- Warnings first, whether or not the compile then failed: they were reported before whatever
    -- error follows them.
    (result.renderWarnings flags lines).forM spinner.log

    -- A driver error ends the spinner with "Build failed."; a failure in a pass past the driver
    -- reports "Compilation failed." without touching the spinner. The third case is
    -- unreachable — an error always renders — and just falls through to the success path.
    match result.error, result.renderError flags lines with
    | some (.driver _), some line =>
      -- Print the error *before* ending the spinner: "Build failed" is the final word, not a
      -- banner ahead of the detail.
      spinner.log line
      spinner.fail "Build failed."
      IO.Process.exit 1
    | some _, some line =>
      spinner.log line
      -- `exit` below skips `withProgress`'s cleanup, so the animation has to be ended here.
      spinner.stop "Compilation failed."
      IO.Process.exit 1
    | _, _ => pure ()

    -- `-o` names a *file*, not a directory: a compile produces exactly one Go file. Everything
    -- lands in one package, and the only thing that could split it — a file per process — would
    -- buy nothing, since Go compiles a package as a unit and the declarations reference each
    -- other freely. Parent directories are created, so `-o build/spec.go` works without a mkdir.
    if let some code := result.go then
      match flags.output with
      | some path =>
        if let some dir := path.parent then
          IO.FS.createDirAll dir
        IO.FS.writeFile path code
      -- Through the spinner, not `IO.println`: standard output is not the handle the animation
      -- is drawn on, but it is the same terminal, so the emitted file has to be sequenced
      -- against the animation like any other line.
      | none => spinner.logOn (← IO.getStdout) code

    spinner.success s!"Build completed successfully ({(← done.get).size} job{if (← done.get).size = 1 then "" else "s"})."
  return 0

/-- The page `fugue explain` prints for `code`: the one at `$FUGUE_DOCS/<code>.md` when that
variable is set — for editing a page without a rebuild — otherwise the copy embedded at build time
(`Diagnostics.embeddedPages`, generated from `docs/diagnostics/`), so an installed binary needs no
files beside it. `none` when no page has been written for the code. -/
private def diagnosticPage (code : DiagnosticCode) : IO (Option String) := do
  if let some dir ← IO.getEnv "FUGUE_DOCS" then
    let path := (dir : System.FilePath) / s!"{code}.md"
    if ← path.pathExists then
      return some (← IO.FS.readFile path)
    return none
  return (Diagnostics.embeddedPages.find? (·.1 == toString code)).map (·.2)

-- The embedded corpus and the registry must agree: every registered code has a
-- `docs/diagnostics/<code>.md`, and every page corresponds to a registered code. A new diagnostic
-- without its page — or a page whose code was never registered — fails the build here rather than
-- shipping a gap.
#guard Diagnostics.entries.all λ e ↦ Diagnostics.embeddedPages.any (·.1 == toString e.code)
#guard Diagnostics.embeddedPages.all λ p ↦ Diagnostics.entries.any (toString ·.code == p.1)

/-- One registry entry, as `fugue explain --list` prints it. -/
private def Diagnostics.Entry.listLine (entry : Diagnostics.Entry) : String :=
  let code := ToString.toString entry.code
  let stage := entry.stage.name
  s!"{code}{String.replicate (8 - code.length) ' '}{stage}{String.replicate (16 - stage.length) ' '}{entry.summary}"

/-- Joke answers for the codes at the two ends of the numbering and one that never existed. None is
a `Diagnostics.entries` member, so `fugue explain --list` never lists them and the registry/page
parity `#guard`s never ask for a `docs/diagnostics/` file; `explainCode` reaches them only after a
code parses and resolves to no registered diagnostic. -/
private def explainEasterEgg? (code : DiagnosticCode) : Option String :=
  let page (summary reporter : String) (body : List String) : String :=
    s!"{code}: {summary}\nReported by: {reporter}\n\n{String.intercalate " " body}"
  match toString code with
  | "E0000" => some <| page "everything is fine." "a clean build"
      [ "Nothing went wrong. Not quietly, not subtly — nothing. You asked the compiler to"
      , "explain the absence of a problem and it has complied. No steps to reproduce." ]
  | "W0000" => some <| page "nothing worth mentioning." "a clean build"
      [ "The compiler has nothing to warn you about. It would like you to know it checked."
      , "It checked thoroughly. W0000 is the receipt." ]
  | "E9999" => some <| page "held in reserve." "the kernel"
      [ "The last error code. The compiler has assigned sixty-odd and is holding this one back"
      , "— not for anything specific, it just dislikes the idea of reaching the end of the list"
      , "with nothing in reserve." ]
  | "W9999" => some <| page "as high as it goes." "arithmetic"
      [ "There is no W10000. Raise nine thousand nine hundred and ninety-nine distinct kinds of"
      , "warning and the compiler will consider a fifth digit. Until then this is the ceiling"
      , "and you are nowhere near it." ]
  | "W0666" => some <| page "nothing untoward." "the daemon"
      [ "Not a real code. You know which number you typed. The compiler knows too. Neither of"
      , "you needs to make it weird." ]
  | _ => none

-- Exactly the codes matched above, none of them registered: if a real diagnostic is ever given
-- one of these numbers, this fails rather than letting the joke shadow it.
#guard ["E0000", "W0000", "E9999", "W9999", "W0666"].all λ s ↦
  match DiagnosticCode.ofString? s with
  | some c => (explainEasterEgg? c).isSome && (Diagnostics.find? c).isNone
  | none => false

/-- Print everything known about one code: its registry entry, then its page if one has been
written. Returns whether `explain` had an answer — a registered code, or one of the joke codes
`explainEasterEgg?` covers. -/
private def explainCode (raw : String) : IO Bool := do
  let some code := DiagnosticCode.ofString? raw
    | IO.eprintln s!"error: '{raw}' is not a diagnostic code. Codes look like 'E0042' or 'W0003'."
      return false
  let some entry := Diagnostics.find? code
    | if let some easterEgg := explainEasterEgg? code then
        IO.println easterEgg
        return true
      IO.eprintln s!"error: no diagnostic is registered under '{code}'. \
Run 'fugue explain --list' to see every code."
      return false
  IO.println s!"{code}: {entry.summary}"
  IO.println s!"Reported by: {entry.stage.name}"
  unless entry.warningName.isEmpty do
    IO.println s!"Suppress with: -Wno-{entry.warningName}"
  IO.println ""
  match ← diagnosticPage code with
  | some text => IO.println text
  | none => IO.println s!"No detailed page for {code} has been written yet."
  return true

private def runExplain (p : Parsed) : IO UInt32 := do
  let codes := p.variableArgsAs! String
  if p.hasFlag "list" then
    Diagnostics.entries.forM λ entry ↦ IO.println entry.listLine
    return 0
  if codes.isEmpty then
    IO.eprintln "error: 'fugue explain' needs a diagnostic code, e.g. 'fugue explain E0042'. \
Use '--list' to see every code."
    return 1
  let mut ok := true
  for raw in codes do
    unless ← explainCode raw do
      ok := false
  return if ok then 0 else 1

private def runHelp (p : Parsed) : IO UInt32 := do
  match HelpTopic.list.filter (λ t ↦ p.hasFlag t.longFlag) with
  | [] =>
    IO.println "Detailed help for the `compile` flags that take a table of names."
    IO.println "Pass one of these to see what names it accepts:"
    IO.println ""
    HelpTopic.list.forM λ t ↦ IO.println s!"  -{t.flag}  {t.summary}"
    IO.println ""
    IO.println "Run `fugue compile --help` for the flags themselves, and `fugue explain <code>` \
for a diagnostic."
  | topics => topics.forM (·.print)
  return 0

/-! `leanprover/Cli` takes an identifier as well as a string literal where a description goes, so
each of these four is `HelpTopic.flagDescription` rather than a hand-written second copy of it. -/

/-- `-d`'s description in `fugue compile --help`. -/
private def debugFlagDescription : String := HelpTopic.debug.flagDescription

/-- `-f`'s description in `fugue compile --help`. -/
private def featureFlagDescription : String := HelpTopic.feature.flagDescription

/-- `-W`'s description in `fugue compile --help`. -/
private def warnFlagDescription : String := HelpTopic.warn.flagDescription

/-- `-X`'s description in `fugue compile --help`. -/
private def targetFlagDescription : String := HelpTopic.target.flagDescription

private def compileCmd : Cmd := `[Cli|
  compile VIA runCli; [fugueVersion]
  "Compile a TLA+ module."

  FLAGS:
    o, output : System.FilePath; "Write the compiled code to this file. Defaults to standard output."
    t, target : Target; "Which backend to target: `go` or `join`. Defaults to `go`."
    "I", "include" : Array System.FilePath; "Add a module search path. Comma-separate to add several: `-I dir1,dir2`."
    -- Each of these names no individual option: the list lives in one place, `HelpTopic.options`,
    -- and is printed by `fugue help` and by the error for an unknown name.
    d, debug : Array NamedOption; debugFlagDescription
    f, feature : Array NamedOption; featureFlagDescription
    "W", warn : Array WarningToggle; warnFlagDescription
    "X", "X" : Array NamedOption; targetFlagDescription

  ARGS:
    input : Input; "The input TLA+ file to compile, or `-` to read from standard input."
]

private def explainCmd : Cmd := `[Cli|
  explain VIA runExplain; [fugueVersion]
  "Explain a diagnostic code, e.g. 'fugue explain E0042'."

  FLAGS:
    l, list; "List every diagnostic code with its stage and summary."

  ARGS:
    ...codes : String; "The codes to explain."
]

private def helpCmd : Cmd := `[Cli|
  help VIA runHelp; [fugueVersion]
  "Explain what names `compile`'s `-d`/`-f`/`-W`/`-X` flags accept."

  FLAGS:
    d, debug; "List the debugging options `-d` accepts."
    f, feature; "List the feature toggles `-f` accepts."
    "W", warn; "List the warnings `-W` controls."
    "X", "X"; "List the backend options `-X` accepts."
]

private def cli : Cmd := `[Cli|
  "fugue" NOOP; [fugueVersion]
  "Fugue — a verified compiler for Distributed PlusCal targeting Go and the Join Calculus."

  SUBCOMMANDS: compileCmd; explainCmd; helpCmd
]

/-- The `fugue` executable's entry point. -/
def main (args : List String) : IO UInt32 := cli.validate args

end
