import Extra.Topology.IMetricSpace
import Extra.Topology.IMetricSpace.Constructions.Bool
import Extra.Topology.IMetricSpace.Constructions.Closeds
import Extra.Topology.IMetricSpace.Constructions.Function
import Extra.Topology.IMetricSpace.Constructions.Int
import Extra.Topology.IMetricSpace.Constructions.List
import Extra.Topology.IMetricSpace.Constructions.Product
import Extra.Topology.IMetricSpace.Constructions.Option
import Extra.Topology.IMetricSpace.Constructions.Restriction
import Extra.Topology.IMetricSpace.Constructions.String
import Extra.Topology.IMetricSpace.Constructions.Sum
