// Command lamport_mutex runs one node of the compiled Lamport's distributed mutual-exclusion
// example (LamportMutex.tla, in this same directory) as a standalone OS process, reachable by
// its peers over TCP through the name-server-mediated wiring in runtime/comm/tcp.
//
// spec/spec.go is generated by fugue compile, not checked in (see spec/doc.go); regenerate it
// with:
//
//	go generate ./examples/lamport_mutex/spec
//
// Bring up a full three-node system locally with run.sh, or by hand:
//
//	go run ./examples/lamport_mutex/nameserver -bind 127.0.0.1:9000
//	go run ./examples/lamport_mutex -name n1 -bind 127.0.0.1:9101 -ns 127.0.0.1:9000
//	go run ./examples/lamport_mutex -name n2 -bind 127.0.0.1:9102 -ns 127.0.0.1:9000
//	go run ./examples/lamport_mutex -name n3 -bind 127.0.0.1:9103 -ns 127.0.0.1:9000
//
// Each process registers under -name with the name server, then looks up every node --
// including itself -- before starting Proc_node; processes may be started in any order because
// Lookup parks until the name it wants appears.
package main

import (
	"flag"
	"log"

	"github.com/mesabloo/fugue/examples/lamport_mutex/spec"
	"github.com/mesabloo/fugue/runtime/comm"
	"github.com/mesabloo/fugue/runtime/comm/tcp"
	"github.com/mesabloo/fugue/runtime/debug"
	"github.com/mesabloo/fugue/runtime/tlaplus"
)

// Msg mirrors the network[self] mailbox message record spec.go spells out inline, field for
// field and in the same order (Go struct identity is order-sensitive).
type Msg = struct {
	Agent comm.Address
	Clock tlaplus.Int
	Type  tlaplus.Str
}

func main() {
	name := flag.String("name", "", "this node's name (one of n1, n2, n3)")
	bind := flag.String("bind", "127.0.0.1:0", "address to listen on for this node's mailbox")
	ns := flag.String("ns", "127.0.0.1:9000", "name server address")
	flag.Parse()

	if !spec.ValidNodeName(*name) {
		log.Fatalf("-name must be one of %v, got %q", spec.NodeNames, *name)
	}
	self := tcp.Name(*name)

	rawMailbox, addr, err := tcp.Listen[Msg](*bind)
	if err != nil {
		log.Fatalf("listen on %s: %v", *bind, err)
	}
	mailbox := debug.LogReceiver(self, rawMailbox)
	if err := tcp.Register(*ns, *name, addr); err != nil {
		log.Fatalf("register %s with name server at %s: %v", *name, *ns, err)
	}
	log.Printf("%s: listening on %s, registered with name server at %s", *name, addr, *ns)

	// LamportMutex.tla's "try" thread multicasts its Request to the full Nodes set, itself
	// included (req[self]/ack are also updated locally in the same step, so the self-addressed
	// copy is redundant with that -- but Multicast panics on a target with no channel entry, so
	// network needs one for every name in NodeNames, self not excluded).
	network := make(map[comm.Address]comm.Sender[Msg], len(spec.NodeNames))
	for _, peer := range spec.NodeNames {
		peerAddr, err := tcp.Lookup(*ns, peer)
		if err != nil {
			log.Fatalf("lookup %s: %v", peer, err)
		}
		network[tcp.Name(peer)] = debug.LogSender(self, tcp.Name(peer), tcp.Dial[Msg](peerAddr))
		log.Printf("%s: resolved peer %s at %s", *name, peer, peerAddr)
	}

	net := spec.Net_Network{Network: network}
	done := spec.Proc_node(net, mailbox, self)
	<-done // Proc_node's two threads both loop forever; this blocks forever too.
}
