// Command paxos runs one node of the compiled Paxos example
// (Paxos.tla, in this same directory) as a standalone OS process, reachable
// by its peers over TCP through the name-server-mediated wiring in
// runtime/comm/tcp.
//
// paxos.go is generated by fugue compile, not checked in (see .gitignore); regenerate it with:
//
//	go generate ./examples/paxos
//
// (needs .lake/build/bin/fugue built — `lake build fugue`; `go generate` runs a directive from
// the package directory, hence the `cd` below, rather than fugue.sh's dev-mode debug-dump
// wrapper, which assumes it runs from the repo root and isn't meant for scripted use like this.)
//
// Bring up a full three-node system locally with run.sh, or by hand:
//
//	go run ./examples/paxos/nameserver -bind 127.0.0.1:9000
//	go run ./examples/paxos -name n1 -bind 127.0.0.1:9101 -ns 127.0.0.1:9000
//	go run ./examples/paxos -name n2 -bind 127.0.0.1:9102 -ns 127.0.0.1:9000
//	go run ./examples/paxos -name n3 -bind 127.0.0.1:9103 -ns 127.0.0.1:9000
//
// Each process registers under -name with the name server, then looks up
// its two peers there before starting Proc_node; processes may be started
// in any order because Lookup parks until the name it wants appears.
package main

//go:generate sh -c "cd ../.. && .lake/build/bin/fugue compile -o examples/paxos/paxos.go examples/paxos/Paxos.tla"

import (
	"flag"
	"log"

	"github.com/mesabloo/fugue/runtime/comm"
	"github.com/mesabloo/fugue/runtime/comm/tcp"
	"github.com/mesabloo/fugue/runtime/debug"
	"github.com/mesabloo/fugue/runtime/tlaplus"
)

// nodeNames is Paxos.tla's CONSTANT Nodes, fixed for this example: the three
// logical identities a process may run as. -name picks which one this
// process is; N and Quorum_ (in paxos.go) are derived from its length.
var nodeNames = []string{"n1", "n2", "n3"}

// N is Paxos.tla's CONSTANT N.
var N tlaplus.Int = tlaplus.MkInt(len(nodeNames))

// Values is Paxos.tla's CONSTANT Values: the pool a leader's CHOOSE picks a
// proposal from once it has a quorum of "1b" replies carrying no value.
var Values = tlaplus.MkSet(tlaplus.StrOrd, tlaplus.Str("red"), tlaplus.Str("green"), tlaplus.Str("blue"))

// Nodes is Paxos.tla's CONSTANT Nodes. It holds logical identities
// (comm/tcp.Name values), kept apart from the "host:port" each process
// actually binds to — the name server bridges the two at Register/Lookup
// time, not here, so this can be built once at package init.
var Nodes = tlaplus.MkSet(comm.AddressOrd, namesToAddresses(nodeNames)...)

func namesToAddresses(names []string) []comm.Address {
	addrs := make([]comm.Address, len(names))
	for i, n := range names {
		addrs[i] = tcp.Name(n)
	}
	return addrs
}

// Ballot mirrors the <<Int, Address>> pair paxos.go spells out inline at
// every use; declared as an alias (type =) so it is the identical type, not
// a distinct one requiring conversions.
type Ballot = struct {
	Proj1 tlaplus.Int
	Proj2 comm.Address
}

// Msg mirrors the ch[self] message record paxos.go spells out inline, field
// for field and in the same order (Go struct identity is order-sensitive).
type Msg = struct {
	Bal     Ballot
	Leader  comm.Address
	MaxVBal Ballot
	MaxVal  tlaplus.Str
	Type    tlaplus.Str
	Val     tlaplus.Str
}

func main() {
	name := flag.String("name", "", "this process's node name (one of n1, n2, n3)")
	bind := flag.String("bind", "127.0.0.1:0", "address to listen on for this node's mailbox")
	ns := flag.String("ns", "127.0.0.1:9000", "name server address")
	flag.Parse()

	if !isNodeName(*name) {
		log.Fatalf("-name must be one of %v, got %q", nodeNames, *name)
	}
	self := tcp.Name(*name)

	rawMailbox, addr, err := tcp.Listen[Msg](*bind)
	if err != nil {
		log.Fatalf("listen on %s: %v", *bind, err)
	}
	mailbox := debug.LogReceiver(self, rawMailbox)
	if err := tcp.Register(*ns, *name, addr); err != nil {
		log.Fatalf("register %s with name server at %s: %v", *name, *ns, err)
	}
	log.Printf("%s: listening on %s, registered with name server at %s", *name, addr, *ns)

	ch := make(map[comm.Address]comm.Sender[Msg], len(nodeNames)-1)
	for _, peer := range nodeNames {
		if peer == *name {
			continue
		}
		peerAddr, err := tcp.Lookup(*ns, peer)
		if err != nil {
			log.Fatalf("lookup %s: %v", peer, err)
		}
		ch[tcp.Name(peer)] = debug.LogSender(self, tcp.Name(peer), tcp.Dial[Msg](peerAddr))
		log.Printf("%s: resolved peer %s at %s", *name, peer, peerAddr)
	}

	net := Net_Network{Ch: ch}
	done := Proc_node(net, mailbox, self)
	<-done // Proc_node's main and helper threads both loop forever; this blocks forever too.
}

func isNodeName(name string) bool {
	for _, n := range nodeNames {
		if n == name {
			return true
		}
	}
	return false
}
