// Command paxos runs one node of the compiled Paxos example
// (Paxos.tla, in this same directory) as a standalone OS process, reachable
// by its peers over TCP through the name-server-mediated wiring in
// runtime/comm/tcp.
//
// spec/spec.go is generated by fugue compile, not checked in (see spec/doc.go);
// regenerate it with:
//
//	go generate ./examples/paxos/spec
//
// Bring up a full three-node system locally with run.sh, or by hand:
//
//	go run ./examples/paxos/nameserver -bind 127.0.0.1:9000
//	go run ./examples/paxos -name n1 -bind 127.0.0.1:9101 -ns 127.0.0.1:9000
//	go run ./examples/paxos -name n2 -bind 127.0.0.1:9102 -ns 127.0.0.1:9000
//	go run ./examples/paxos -name n3 -bind 127.0.0.1:9103 -ns 127.0.0.1:9000
//
// Each process registers under -name with the name server, then looks up
// its two peers there before starting Proc_node; processes may be started
// in any order because Lookup parks until the name it wants appears.
package main

import (
	"flag"
	"log"

	"github.com/mesabloo/fugue/examples/paxos/spec"
	"github.com/mesabloo/fugue/runtime/comm"
	"github.com/mesabloo/fugue/runtime/comm/tcp"
	"github.com/mesabloo/fugue/runtime/debug"
	"github.com/mesabloo/fugue/runtime/tlaplus"
)

// Ballot mirrors the <<Int, Address>> pair spec.go spells out inline at
// every use; declared as an alias (type =) so it is the identical type, not
// a distinct one requiring conversions.
type Ballot = struct {
	Proj1 tlaplus.Int
	Proj2 comm.Address
}

// Msg mirrors the ch[self] message record spec.go spells out inline, field
// for field and in the same order (Go struct identity is order-sensitive).
type Msg = struct {
	Bal     Ballot
	Leader  comm.Address
	MaxVBal Ballot
	MaxVal  tlaplus.Str
	Type    tlaplus.Str
	Val     tlaplus.Str
}

func main() {
	name := flag.String("name", "", "this process's node name (one of n1, n2, n3)")
	bind := flag.String("bind", "127.0.0.1:0", "address to listen on for this node's mailbox")
	ns := flag.String("ns", "127.0.0.1:9000", "name server address")
	flag.Parse()

	if !spec.ValidNodeName(*name) {
		log.Fatalf("-name must be one of %v, got %q", spec.NodeNames, *name)
	}
	self := tcp.Name(*name)

	rawMailbox, addr, err := tcp.Listen[Msg](*bind)
	if err != nil {
		log.Fatalf("listen on %s: %v", *bind, err)
	}
	mailbox := debug.LogReceiver(self, rawMailbox)
	if err := tcp.Register(*ns, *name, addr); err != nil {
		log.Fatalf("register %s with name server at %s: %v", *name, *ns, err)
	}
	log.Printf("%s: listening on %s, registered with name server at %s", *name, addr, *ns)

	ch := make(map[comm.Address]comm.Sender[Msg], len(spec.NodeNames)-1)
	for _, peer := range spec.NodeNames {
		if peer == *name {
			continue
		}
		peerAddr, err := tcp.Lookup(*ns, peer)
		if err != nil {
			log.Fatalf("lookup %s: %v", peer, err)
		}
		ch[tcp.Name(peer)] = debug.LogSender(self, tcp.Name(peer), tcp.Dial[Msg](peerAddr))
		log.Printf("%s: resolved peer %s at %s", *name, peer, peerAddr)
	}

	net := spec.Net_Network{Ch: ch}
	done := spec.Proc_node(net, mailbox, self)
	<-done // Proc_node's main and helper threads both loop forever; this blocks forever too.
}
