name: Build project

on:
  push:
    branches: 
    - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Read access to repository contents

jobs:
  build:
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Build and lint the project
        id: build-lean
        uses: leanprover/lean-action@v1.4.0
        with:
          auto-config: false
          build: true
          test: true 
          lint: false
          mk_all-check: false
          use-mathlib-cache: true