name: Build documentation and deploy

on:
  workflow_run:
    workflows: ["Build project"]
    types: [completed]
    branches: 
    - main

permissions:
  contents: read # Read access to repository contents
  id-token: write # Required to upload the site to GitHub Pages
  pages: write # Write access to GitHub Pages

jobs:
  doc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        # with:
        #   fetch-depth: 0 # Fetch all history for all branches and tags

      - uses: leanprover/lean-action@v1.4.0
        with:
          auto-config: false
          build: false
          test: false 
          lint: false
          mk_all-check: false
          use-mathlib-cache: false

      - name: Run lake translate-config toml
        continue-on-error: true
        run: |
          lake translate-config toml || exit 0

      - name: Build project documentation
        id: build-docgen
        uses: leanprover-community/docgen-action@7836f3de2f10facc0fed09c1309e6402e4cd5fd0
        with:
          api-docs: false
          build-page: false
          blueprint: false