name: Rebase onto `docs`

on:
  workflow_run:
    workflows: ["Build project"]
    types: [completed]
    branches: 
    - main

permissions:
  contents: read # Read access to repository contents

jobs:
  doc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
        #   fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Rebase onto `docs` to trigger workflow
        uses: martincostello/rebaser@v1
        id: rebase
        with:
          branch: docs

      - name: Push
        if : ${{ steps.rebase.outputs.result == 'success' }}
        run: git push --force-with-lease origin docs